/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package ProffSkillsAssignment1;
import java.time.LocalDate;
import java.time.Month;
import java.util.ArrayList;
public class App {
    public String getGreeting() {
        return "Hello World!";
    }

}    